server-damage-multiplier: 1.0
menu:
  type: simple # simple or advanced or command to execute instead
  command: "openmenu"
mining-blacklisted-worlds: []
actionbar:
  # The actionbar is the text that appears at the bottom of the screen.
  # You can use the following placeholders:
  # <health> - Current health of the player
  # <max-health> - Maximum health of the player
  # <defense> - Current defense of the player
  # <mana> - Current mana of the player
  # <max-mana> - Maximum mana of the player
  # <stat> - Stat of the player example: speed
  # Make sure to put [] if you want alerts to be shown in the actionbar.
  # Text in [] will be replaced with the alert for a few seconds.
  enabled: true
  format: <red><health>/<max-health>❤ [<green><defense>❈] <aqua><mana>/<max-mana>✎
skill-need-xp:
  - 100.0
  - 200.0
  - 300.0
  - 400.0
  - 500.0
  - 600.0
  - 700.0
  - 800.0
  - 900.0
  - 1000.0
  - 1100.0
  - 1200.0
  - 1300.0
  - 1400.0
  - 1500.0
  - 1600.0
  - 1700.0
  - 1800.0
  - 1900.0
  - 2000.0
  - 2100.0
  - 2200.0
  - 2300.0
  - 2400.0
  - 2500.0
  - 2600.0
  - 2700.0
  - 2800.0
  - 2900.0
  - 3000.0
  - 3100.0
  - 3200.0
  - 3300.0
  - 3400.0
  - 3500.0
  - 3600.0
  - 3700.0
  - 3800.0
  - 3900.0
  - 4000.0
  - 4100.0
  - 4200.0
  - 4300.0
  - 4400.0
  - 4500.0
  - 4600.0
  - 4700.0
  - 4800.0
  - 4900.0
  - 5000.0
griffin: # Warning! This is a work in progress and may not be fully functional yet.
  world: "griffin"
  start-location:
    x: 0
    y: 0
    z: 0
  end-location:
    x: 0
    y: 0
    z: 0